version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:5672"
      - "25672:15672"

  redis:
    image: "redis:alpine"
    ports:
      - "16379:6379"
    logging:
      driver: none

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=real_estate
      - POSTGRES_USER=real_estate
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
